refactor: migrate packages into additional-components
bcakmakoglu/vue-flow pull request #1200
Opened 2023-11-17 14:48 UTC by michealroberts

refactor: migrate packages into additional-components

# 🚀 What's changed?

- Migrated Background package into @vue-flow/core additional components
- Migrated Controls package into @vue-flow/core additional components
- Migrated MiniMap package into @vue-flow/core additional components
- Migrated NodeResizer package into @vue-flow/core additional components
- Migrated NodeToolbar package into @vue-flow/core additional components
- Migrated PathfindingEdge package into @vue-flow/core additional components

The migration is backwards compatible, meaning imports from e.g.,:

```ts
import { Background } from '@vue-flow/background'
```

will still work. 

However, the user will see a deprecation notice.

The current vite app has had zero changes, yet still works as before:

![CleanShot 2023-11-17 at 14 45 58](https://github.com/bcakmakoglu/vue-flow/assets/84131395/a326b0b7-41fb-4778-b47b-382b45a1934b)

# Misc 🧷 

This MR includes a few smaller refactors to gather type import / exports with variable imports / exports, e.g.,:

Before:

```ts
import { zoom, zoomIdentity } from 'd3-zoom'
import type { D3ZoomEvent } from 'd3-zoom'
```

After:

```ts
import { type D3ZoomEvent, zoom, zoomIdentity } from 'd3-zoom'
```

2023-11-17 15:01 UTC, michealroberts commented
@braks The motive for this PR is that we can:

- Provide Vue 2 backwards compatibility in the not to distant future
- Improve discoverability of features
- Make utilisation of xyflow/system easier in the future
- Align with xyflow/react and xyflow/svelte

2023-11-21 09:39 UTC, michealroberts commented
> I think we can remove the pathfinding edge from the migration - it's gonna be eliminated soon anyway
> 
> It's not really used, it's not updated to support the latest Vue Flow version neither and I don't have the time to maintain it either 😄

Ok cool. I'll  leave the package as is in `@vue-flow/pathfinding-edge`.

2023-11-23 15:35 UTC, bcakmakoglu commented on packages/core/src/additional-components/Background/Background.vue
> +import { useVueFlow } from '~/composables'
There's a problem with using tsconfig shortcut paths inside vue component, as they're not resolved to the actual paths when the build is triggered.

This works in `.ts` files thanks to `ts-transform-paths` but, alas, not in `.vue` files -.-

So this sadly has to be `../../../composables/useVueFlow`

2023-11-23 15:38 UTC, bcakmakoglu requested changes

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/Background/Background.vue
> +import { useVueFlow } from '~/composables'
There's a problem with using tsconfig shortcut paths inside vue component, as they're not resolved to the actual paths when the build is triggered.

This works in `.ts` files thanks to `ts-transform-paths` but, alas, not in `.vue` files -.-

So this sadly has to be `../../../composables/useVueFlow`

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/Controls/Controls.vue
> +import { PanelPosition } from '~/types'
See my previous comment about shortcut paths

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/MiniMap/MiniMap.vue
> +import { getBoundsofRects, getConnectedEdges, getRectOfNodes } from '~/utils'
Same here

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/NodeResizer/NodeResizer.vue
> +import { type NodeDimensionChange } from '~/types'
And here 😄

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/NodeResizer/ResizeControl.vue
> +import { clamp } from '~/utils'
And also here

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/NodeToolbar/NodeToolbar.vue
> +import { getRectOfNodes } from '~/utils'
Here as well

2023-11-23 15:38 UTC, bcakmakoglu commented on packages/core/src/additional-components/index.ts
> +export * from '../../../pathfinding-edge/src'
This line can be removed

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/Controls/Controls.vue
> +import { PanelPosition } from '~/types'
Amended ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/MiniMap/MiniMap.vue
> +import { getBoundsofRects, getConnectedEdges, getRectOfNodes } from '~/utils'
Amended ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/NodeResizer/NodeResizer.vue
> +import { type NodeDimensionChange } from '~/types'
Amended ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/NodeResizer/ResizeControl.vue
> +import { clamp } from '~/utils'
Amended ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/index.ts
> +export * from '../../../pathfinding-edge/src'
Done ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/NodeToolbar/NodeToolbar.vue
> +import { getRectOfNodes } from '~/utils'
Amended ✅

2023-11-23 16:11 UTC, michealroberts commented on packages/core/src/additional-components/NodeResizer/ResizeControl.vue
> +import { clamp } from '~/utils'
Amended ✅

2023-11-24 07:08 UTC, bcakmakoglu commented
Did you try to lint before comitting?

```ts
import { type PanelPosition } from '...'
```

This should give you an error by ESLint/TS as `PanelPosition` is an enum and used as an enum (hence we get an error when trying to build in this branch and the docs can't be deployed)

2023-11-24 08:52 UTC, michealroberts commented
> Did you try to lint before comitting?
> 
> ```ts
> import { type PanelPosition } from '...'
> ```
> 
> This should give you an error by ESLint/TS as `PanelPosition` is an enum and used as an enum (hence we get an error when trying to build in this branch and the docs can't be deployed)

Yeh, 7 our of 7 successful. I think maybe it's not picking up on it because it is also deprecated.

Regardless, I have amended.

2023-11-24 08:55 UTC, michealroberts commented
@bcakmakoglu Should I also amend docs about the usage going forward, and any deprecation notices?

2023-11-24 13:32 UTC, bcakmakoglu commented
Mh... makes sense I'd say, otherwise we'll be stuck having to update the docs at the end and nobody will remember what has to be changed 😄

2023-11-25 08:36 UTC, bcakmakoglu approved these changes
Except for the docs part, the PR looks good to me :)

2023-11-25 08:56 UTC, michealroberts commented
> Except for the docs part, the PR looks good to me :)

Nice. Will update the docs ASAP.

2024-02-03 17:08 UTC, closed without merging

2024-02-15 20:53 UTC, bcakmakoglu commented
Didn't mean to close this Pr :/
Dropped the old vue2 branch since it started to heavily conflict (there are some features that were added still 😅)

I'll take the changes from here and open a new PR to move the components into the core pkg